# Site settings
title: Full Stack Journey
header-img: img/home-bg.png
email: ktamoguis@gmail.com
copyright_name: ktamoguis
description: > # this means to ignore newlines until "baseurl:"
  Learnings in Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ktamoguis
learn_profile: ktamoguis
email_username: ktamoguis@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
